apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: {{ b64enc .Values.postgres.username }}
  POSTGRES_PASSWORD: {{ b64enc .Values.postgres.password }}
  POSTGRES_DB: {{ b64enc .Values.postgres.db }}
